package com.jerry.blescanner.jetpack_design_lib.theme

import androidx.compose.ui.graphics.Color

val vusion_theme_light_primary = Color(0xFF8307F0)
val vusion_theme_light_onPrimary = Color(0xFFFFFFFF)
val vusion_theme_light_primaryContainer = Color(0xFFEEDCFF)
val vusion_theme_light_onPrimaryContainer = Color(0xFF2A0054)
val vusion_theme_light_secondary = Color(0xFF655A6F)
val vusion_theme_light_onSecondary = Color(0xFFFFFFFF)
val vusion_theme_light_secondaryContainer = Color(0xFFEBDDF7)
val vusion_theme_light_onSecondaryContainer = Color(0xFF20182A)
val vusion_theme_light_tertiary = Color(0xFF80525A)
val vusion_theme_light_onTertiary = Color(0xFFFFFFFF)
val vusion_theme_light_tertiaryContainer = Color(0xFFFFD9DE)
val vusion_theme_light_onTertiaryContainer = Color(0xFF321018)
val vusion_theme_light_error = Color(0xFFBA1A1A)
val vusion_theme_light_errorContainer = Color(0xFFFFDAD6)
val vusion_theme_light_onError = Color(0xFFFFFFFF)
val vusion_theme_light_onErrorContainer = Color(0xFF410002)
val vusion_theme_light_background = Color(0xFFFFFBFF)
val vusion_theme_light_onBackground = Color(0xFF1D1B1E)
val vusion_theme_light_surface = Color(0xFFFFFBFF)
val vusion_theme_light_onSurface = Color(0xFF1D1B1E)
val vusion_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val vusion_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val vusion_theme_light_outline = Color(0xFF7B757F)
val vusion_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val vusion_theme_light_inverseSurface = Color(0xFF1D1B1E)
val vusion_theme_light_inversePrimary = Color(0xFFD9B9FF)
val vusion_theme_light_shadow = Color(0xFF000000)
val vusion_theme_light_surfaceTint = Color(0xFF8307F0)

val vusion_theme_dark_primary = Color(0xFFD9B9FF)
val vusion_theme_dark_onPrimary = Color(0xFF450085)
val vusion_theme_dark_primaryContainer = Color(0xFF6300BA)
val vusion_theme_dark_onPrimaryContainer = Color(0xFFEEDCFF)
val vusion_theme_dark_secondary = Color(0xFFCFC1DA)
val vusion_theme_dark_onSecondary = Color(0xFF352D40)
val vusion_theme_dark_secondaryContainer = Color(0xFF4C4357)
val vusion_theme_dark_onSecondaryContainer = Color(0xFFEBDDF7)
val vusion_theme_dark_tertiary = Color(0xFFF2B7C1)
val vusion_theme_dark_onTertiary = Color(0xFF4B252D)
val vusion_theme_dark_tertiaryContainer = Color(0xFF653B43)
val vusion_theme_dark_onTertiaryContainer = Color(0xFFFFD9DE)
val vusion_theme_dark_error = Color(0xFFFFB4AB)
val vusion_theme_dark_errorContainer = Color(0xFF93000A)
val vusion_theme_dark_onError = Color(0xFF690005)
val vusion_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val vusion_theme_dark_background = Color(0xFF1D1B1E)
val vusion_theme_dark_onBackground = Color(0xFFE7E1E5)
val vusion_theme_dark_surface = Color(0xFF1D1B1E)
val vusion_theme_dark_onSurface = Color(0xFFE7E1E5)
val vusion_theme_dark_surfaceVariant = Color(0xFF4A454E)
val vusion_theme_dark_onSurfaceVariant = Color(0xFFCCC4CF)
val vusion_theme_dark_outline = Color(0xFF958E99)
val vusion_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val vusion_theme_dark_inverseSurface = Color(0xFFFFFBFF)
val vusion_theme_dark_inversePrimary = Color(0xFF8307F0)
val vusion_theme_dark_shadow = Color(0xFF000000)
val vusion_theme_dark_surfaceTint = Color(0xFFD9B9FF)

val seed = Color(0xFF8100EF)
val error = Color(0xFFB3261E)
